@startuml
'https://plantuml.com/class-diagram

class Solution42
{
    +{static} void main(String[] args)
}

class CSVToTabular
{
    ' Fields
    -ArrayList<ArrayList<String>> data
    -Path currentPath
    -String[] headerLabels

    ' User interface
    +void readCSV(String inputFileName)
    +String employeeCSVToTable()

    ' Helper methods
    -Path getPathFromFileName(String fileName)
    -int getDividerLength()
    -int getFieldWidth(int column)

    ' Accessor methods for testing
    +List<ArrayList<String>> getData()
}

Solution42 o-- CSVToTabular

@enduml