@startuml
'https://plantuml.com/class-diagram

class Solution42
{
    +{static} void main(String[] args)
}

class CSVToTabular
{
    -ArrayList<ArrayList<String>> data
    -Path currentPath
    -String[] header

    -Path getPathFromFileName(String fileName)
    +void readCSV(String inputFileName)
    +String employeeCSVToTable()
    -int getDividerLength()
    -int getFieldWidth(int column)
    +List<ArrayList<String>> getData()
}

Solution42 o-- CSVToTabular

@enduml