@startuml
'https://plantuml.com/class-diagram

class Solution43
{
    -{static} Scanner sc

    +{static} void main(String[] args)
    -boolean getYesNoFromUser(String prompt)
}

class WebsiteGenerator
{
    -Path currentPath
    -Path siteRoot
    -{static} String FILE_CREATION_HEADER
    -String websiteName
    -String authorName
    -boolean createJSFolder
    -boolean createCSSFolder

    +WebsiteGenerator(String websiteName, String authorName, boolean createJSFolder, boolean createCSSFolder)
    +void generateSite()
    -void generateSiteIndex()
    -void createDirAndDisplayPath(String directoryName)
    +String getWebsiteName()
    +String getAuthorName()
}

Solution43 o-- WebsiteGenerator

@enduml