@startuml
'https://plantuml.com/class-diagram

class Solution46
{
    +static void main(String[] args)
}

class WordFrequencyFinder
{
    ' Fields
    -Path currentPath
    -ArrayList<String> words
    -HashMap<String, Integer> freq

    ' User interface
    +void getWordFrequencies(String fileName)
    +void sortWordList()
    +String generateOutput()

    ' Helper methods
    -int getFieldWidth()
    -Path getPathFromFileName(String fileName)

    ' Accessor methods for testing
    +Map<String, Integer> getFrequencyMap()
    +List<String> getWordList()
    
}

Solution46 o-- WordFrequencyFinder

@enduml