@startuml
'https://plantuml.com/class-diagram

class Solution46
{
    +static void main(String[] args)
}

class WordFrequencyFinder
{
    -Path currentPath
    -ArrayList<String> words
    -HashMap<String, Integer> freq

    +void getWordFrequencies(String fileName)
    +void sortWordList()
    +String generateOutput()
    -int getFieldWidth()
    -Path getPathFromFileName(String fileName)
    
}

Solution46 o-- WordFrequencyFinder

@enduml