@startuml
'https://plantuml.com/class-diagram

class Solution44
{
    -{static} Scanner sc

    +{static} void main(String[] args)

    +void searchForProduct(String query)
    -void readJSONFile()
}

class Product
{
    -String name;
    -double price;
    -int quantity;

    +String toString()
}

Solution44 -- Product

@enduml