@startuml
'https://plantuml.com/class-diagram

class Solution44
{
    -{static} Scanner sc
    -Path currentPath
    -Database db

    +{static} void main(String[] args)
    -void readDatabaseFromJSONFile()
}

class Database
{
    -ArrayList<Product> products

    +Database(List<Product>)
    +Map<String, Product> getProductDatabase()
    +String getProductInfo(String query)
}

class Product
{
    -String name;
    -double price;
    -int quantity;

    +Product(String name, double price, int quantity)
    +String getName()
    +String toString()
}

Solution44 -- Database
Database -- Product

@enduml